---
title: "ASFR and TFR using COB data, 17/08/23"
output: 
  html_document:
    css: Wil_style.css
    theme: default
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
always_allow_html: yes
---

```{r setup1, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(zoo)
library(data.table)
library(tidyverse)
library(gglaplot)
library(ggplot2)
library(scales)
library(readxl)
library(knitr)
library(sf)
library(sp)
library(kableExtra)
library(magick)
library(plotly)    
library(RColorBrewer)
library(htmltools)
library(prettydoc)
library(rmdformats)

#devtools::load_all("C:/demogtools/")

data_dir <- 'C:/Families/Data/'
chart_dir <- 'C:/Families/Charts/'
#colour_palette <- gla_colour_palette()[c(3,6,2,4,5,7,1)]

# Disable scientific notation
options(scipen=999)

```


```{r setup2, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

# Read in data 

ASFR_data_wide <- read.csv("C:/Families/Data/ASFR_Mothers_BornInorOutsideUK.csv") %>%
  filter(Age_group != "TFR") %>%   
  data.frame

# reshape
ASFR_data_long <- ASFR_data_wide %>% 
  pivot_longer(
    cols = `X2021`:`X2004`, 
    names_to = "Year",
    values_to = "ASFR")


```


```{r fig_London_ASFR_1, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Line plot of ASFR for London in 2021, calculated by SYA

level_order <- c('Under 20', '20 to 24', '25 - 29', '30 to 34', '35 to 39', '40 and over')

ASFR_2021_line <- ASFR_data_long %>%
  filter(Year == "X2021") %>%
  ggplot(aes(x = Age_group, y = ASFR, group = Location, colour = Location, text = paste("Age-group : ", Age_group,
                         "<br>ASFR: ", round(ASFR, digits = 2))
)) +
  theme_gla() +
  theme(legend.position = "right") +
  geom_line(size = 1) + 
  scale_x_discrete(limits = level_order) +
  ylim(0, 150) +
  labs(title= "Age specific fertility rate by location of mothers' birth, 2021", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggsave (filename = (paste0(chart_dir, "ASFR_COB2021_line.png")),
         plot = ASFR_2021_line,
         device = "png",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")


ASFR_2021_line_int <- ggplotly(ASFR_2021_line, tooltip = "text") %>%
    style(hoverlabel = list(bgcolor = "white")) %>%
    layout(title= list(x = 0.05,
         text = "<b>Age specific fertility rate by location of mothers' birth, 2021<b>", 
         font=list(size = 15, family = "Arial")))
ASFR_2021_line_int


```



```{r fig_London_ASFR_2, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Line plot of ASFR by age-group, showing change between 2004 - 2021 for mothers born in UK

level_order <- c('Under 20', '20 to 24', '25 - 29', '30 to 34', '35 to 39', '40 and over')

ASFR_inUK_line_time <- ASFR_data_long %>%
  filter(Location == "Inside_UK") %>%
  mutate(Year_new = as.numeric(gsub("X","", Year))) %>%
  ggplot(aes(x = Age_group, y = ASFR, group = Year_new, color = Year_new, text = paste("Year  :", Year_new,
                                                           "<br>Age-group : ", Age_group,
                                                          "<br>ASFR: ", round(ASFR, digits = 3))
             )) +
  theme_gla() +
  theme(legend.position = "right") +
  geom_line() + 
  scale_colour_gradient(low = "#edf8e9", high = "#006d2c") +
  scale_x_discrete(limits = level_order) +  
  ylim(0, 150) +
  labs(title= "Age specific fertility rate for mothers born inside UK, 2004 - 2021", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggsave (filename = (paste0(chart_dir, "ASFR_COBinUK_line.png")),
         plot = ASFR_inUK_line_time,
         device = "png",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")

ASFR_inUK_line_time_int <- ggplotly(ASFR_inUK_line_time, tooltip = "text") %>%
    style(hoverlabel = list(bgcolor = "white")) %>%
    layout(title= list(x = 0.05,
         text = "<b>Age specific fertility rate for mothers born inside UK, 2001 - 2021<b>", 
         font=list(size = 15, family = "Arial")))
ASFR_inUK_line_time_int

```

```{r fig_London_ASFR_3, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Line plot of ASFR by age-group, showing change between 2001 - 2021 for mothers born outside UK

level_order <- c('Under 20', '20 to 24', '25 - 29', '30 to 34', '35 to 39', '40 and over')

ASFR_outUK_line_time <- ASFR_data_long %>%
  filter(Location == "Outside_UK") %>%
  mutate(Year_new = as.numeric(gsub("X","", Year))) %>%
  ggplot(aes(x = Age_group, y = ASFR, group = Year_new, color = Year_new, text = paste("Year  :", Year_new,
                                                           "<br>Age-group : ", Age_group,
                                                          "<br>ASFR: ", round(ASFR, digits = 3))
             )) +
  theme_gla() +
  theme(legend.position = "right") +
  geom_line() + 
  scale_colour_gradient(low = "#edf8e9", high = "#006d2c") +
  scale_x_discrete(limits = level_order) +  
  ylim(0, 150) +
  labs(title= "Age specific fertility rate for mothers born inside UK, 2004 - 2021", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggsave (filename = (paste0(chart_dir, "ASFR_COBoutUK_line.png")),
         plot = ASFR_outUK_line_time,
         device = "png",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")


ASFR_outUK_line_time_int <- ggplotly(ASFR_outUK_line_time, tooltip = "text") %>%
    style(hoverlabel = list(bgcolor = "white")) %>%
    layout(title= list(x = 0.05,
         text = "<b>Age specific fertility rate for mothers born inside UK, 2004 - 2021<b>", 
         font=list(size = 15, family = "Arial")))
ASFR_outUK_line_time_int

```



```{r setup3, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

# Read in data 

TFR_data_wide <- read.csv("C:/Families/Data/ASFR_Mothers_BornInorOutsideUK.csv") %>%
  filter(Age_group == "TFR") %>%   
  data.frame

# reshape
TFR_data_long <- TFR_data_wide %>% 
  pivot_longer(
    cols = `X2021`:`X2004`, 
    names_to = "Year",
    values_to = "TFR")

```


```{r fig_London_TFR, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Line plot of TFR by year and location of mothers' birth

level_order <- c('Under 20', '20 to 24', '25 - 29', '30 to 34', '35 to 39', '40 and over')

TFR_line_time <- TFR_data_long %>%
  mutate(Year_new = as.numeric(gsub("X","", Year))) %>%
  mutate(Location_factor = factor(Location, labels = c('All women', 'Inside UK', 'Outside UK'))) %>%
  ggplot(aes(x = Year_new, y = TFR, group = Location, colour = Location_factor, 
                                                text = paste("Year  :", Year_new,
                                                          "<br>Location of birth : ", Location,
                                                           "<br>TFR: ", round(TFR, digits = 3))
             )) +
  theme_gla() +
  theme(legend.position = "right") +
  geom_line(size = 1) + 
  labs(title= "Total fertility rate by location of mothers' birth, 2004 - 2021", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggsave (filename = (paste0(chart_dir, "TFR_COB_line.png")),
         plot = TFR_line_time,
         device = "png",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")

TFR_line_time_int <- ggplotly(TFR_line_time, tooltip = "text") %>%
    style(hoverlabel = list(bgcolor = "white")) %>%
    layout(title= list(x = 0.05,
         text = "<b>Total fertility rate by location of mothers' birth, 2004 - 2021<b>", 
         font=list(size = 15, family = "Arial")))
TFR_line_time_int

```