---
title: "Births analysis, 26th July 2023"
output: 
  html_document:
    css: Wil_style.css
    theme: default
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
always_allow_html: yes
---

```{r setup1, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(zoo)
library(data.table)
library(tidyverse)
library(gglaplot)
library(ggplot2)
library(scales)
library(readxl)
library(knitr)
library(sf)
library(sp)
library(kableExtra)
library(magick)
library(plotly)    
library(RColorBrewer)
library(htmltools)
library(prettydoc)
library(rmdformats)

#devtools::load_all("C:/demogtools/")

data_dir <- 'C:/Families/Data/'
chart_dir <- 'Charts/'
#colour_palette <- gla_colour_palette()[c(3,6,2,4,5,7,1)]

# Disable scientific notation
options(scipen=999)

```


```{r setup2, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

# Using single year of age for calculations rather than 5 year age bands

# Read in births (all years from 1993) 

All_births <- readRDS("C:/Families/Data/Births_by_SYA_1993-2021/births_calendar_year_age_mother_lad.rds") %>%   
  data.frame

# group the extreme ages

All_london_births <- All_births %>%
  filter(grepl('E09000', gss_code)) %>%
  filter(age_mother !="total") %>%
  mutate(age_mother = recode(age_mother, 'Under 20'='19', '40 and over'='40')) %>% 
  mutate(age_mother = as.numeric(age_mother)) %>%
  group_by_(.dots=c("year", "age_mother")) %>% 
  summarize(SUM_births = sum(value)) %>%
  data.frame()
  

# Read in population data again (now this is from 1991) 

input_pop <-  readRDS("C:/Families/GLA_population/pop_1991_2021_age_0to85plus.rds") %>%   
  data.frame()

# select population for London, and only women

London_fempop_fifteenToFortyfour <- input_pop %>%
  filter(sex == "female") %>%
  filter(grepl('E09000', gss_code)) %>%
  filter(age >14) %>%
  filter(age <45) %>%
  mutate(age=replace(age, age<20, 19)) %>%
  mutate(age=replace(age, age>40, 40)) %>%
  group_by(year, age) %>% 
  summarize(SUM_pop = sum(value)) %>%
  data.frame()
  
# Joining population and births data 

merged_births_pop_SYA = left_join(London_fempop_fifteenToFortyfour, All_london_births,
               by=c("year", "age" = "age_mother")) %>%
  filter(year >1992) %>%
  data.frame()

ASFR_calc_SYA <- merged_births_pop_SYA %>%
  mutate(ASFR = SUM_births*1000/SUM_pop) %>%
  data.frame()

TFR_calc_SYA <- ASFR_calc_SYA %>%
  group_by(year) %>% 
  summarise(SUM_ASFR = sum(ASFR)) %>%
  mutate(TFR = SUM_ASFR/1000) %>%
   select(year, SUM_ASFR, TFR) %>%
  data.frame()

```


```{r fig_London_TFR_1, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Line plot of TFR for London 1993 - 2021, calculated by SYA

TFR_line_SYA <- TFR_calc_SYA %>%
    mutate(year_factor = as.factor(year)) %>%
    ggplot(aes(x = year_factor, y = TFR, group = 1, text = paste("Year: ", year,
                         "<br>TFR: ", round(TFR, digits = 3)) 
               )) +
  theme_gla() +
  geom_line(colour = "#739272", size = 1) + 
  ylim(0.5, 3.0) +
  scale_x_discrete(name ="Year", breaks=c("1991", "1996", "2001","2006","2011", "2016", "2021")) +
  labs(title= "TOTAL FERTILITY RATE, London, 1993 - 2021", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggplotly(TFR_line_SYA, tooltip = "text") %>%
    style(hoverlabel = list(bgcolor = "white")) %>%
    layout(title= list(x = 0.05,
         text = "<b>Fig 1: TOTAL FERTILITY RATE, London, 1993 - 2021, calculated using SYA<b>", 
         font=list(size = 15, family = "Arial")))


```


```{r fig_London_TFR_2, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Line plot of ASFR for London in 2021, calculated by SYA

ASFR_2021_line_SYA <- ASFR_calc_SYA %>%
  filter(year == "2021") %>%
  ggplot(aes(x = age, y = ASFR, group = 1, text = paste("Age : ", age,
                         "<br>ASFR: ", round(ASFR, digits = 3))
)) +
  theme_gla() +
  geom_line(colour = "#739272", size = 1) + 
  ylim(0, 150) +
  labs(title= "AGE SPECIFIC FERTILITY RATE, London, 2021, using SYA", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggplotly(ASFR_2021_line_SYA, tooltip = "text") %>%
    style(hoverlabel = list(bgcolor = "white")) %>%
    layout(title= list(x = 0.05,
         text = "<b>Fig 2: AGE SPECIFIC FERTILITY RATE, London, 2021, calculated using SYA<b>", 
         font=list(size = 15, family = "Arial")))



```



```{r fig_London_TFR_3, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Line plot of ASFR by year of age, showing change between 1993 - 2021, calculated by SYA

ASFR_line_SYA <- ASFR_calc_SYA %>%
  ggplot(aes(x = age, y = ASFR, group = year, color = year, text = paste("Year  :", year,
                                                           "<br>Age : ", age,
                                                          "<br>ASFR: ", round(ASFR, digits = 3))
             )) +
  theme_gla() +
  geom_line() + 
  scale_colour_gradient(low = "#edf8e9", high = "#006d2c") +
  ylim(0, 150) +
  labs(title= "Fig 3: AGE SPECIFIC FERTILITY RATE, London, 1993 - 2021, calculated using SYA", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggplotly(ASFR_line_SYA, tooltip = "text") %>%
    style(hoverlabel = list(bgcolor = "white")) %>%
    layout(title= list(x = 0.05,
         text = "<b>Fig 3: AGE SPECIFIC FERTILITY RATE, London, 1993 - 2021, calculated using SYA<b>", 
         font=list(size = 15, family = "Arial")))



```




```{r setup3, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

# Now doing calculations so that can plot ASFR over time by separate age groups

All_births <- readRDS("C:/Families/Data/Births_by_SYA_1993-2021/births_calendar_year_age_mother_lad.rds") %>%   
  data.frame


All_london_births_group <- All_births %>%
  filter(grepl('E09000', gss_code)) %>%
  filter(age_mother != "total") %>%
  mutate(age_mother = recode(age_mother, 'Under 20'='19', '40 and over'='41')) %>% 
  mutate(age_mother_num = as.numeric(age_mother)) %>%
  mutate(age_motherCat = cut(age_mother_num, breaks = c(15, 20, 25, 30, 35, 40, 50),
                      right=FALSE,
                      labels = c("15 - 19",
                                 "20 - 24",
                                 "25 - 29",
                                 "30 - 34",
                                 "35 - 39",
                                 "40 - 44"))) %>%
  data.frame()

All_london_births_agg <- All_london_births_group %>%
  group_by(year, age_motherCat) %>%
  summarize(SUM_births = sum(value)) %>%
  data.frame()

#-----------------------------------------------------------------------

# Reading population data for all years from 1993 

input_pop <-  readRDS("C:/Families/GLA_population/pop_1991_2021_age_0to85plus.rds") %>%   
  data.frame()

# select population for London, and only women
All_london_fempop_group <- input_pop %>%
  filter(sex == "female") %>%
  filter(grepl('E09000', gss_code)) %>%
  mutate(age_Cat = cut(age, breaks = c(0, 15, 20, 25, 30, 35, 40, 45, 50),
                      right=FALSE,
                      labels = c(" 0 - 14",
                                 "15 - 19",
                                 "20 - 24",
                                 "25 - 29",
                                 "30 - 34",
                                 "35 - 39",
                                 "40 - 44",
                                 "45 - 49"))) %>%
  filter(age_Cat != " 0 - 14") %>%
  filter(age_Cat != "45 - 49") %>%
  data.frame()

All_london_fempop_agg <- All_london_fempop_group %>%
  group_by(year, age_Cat) %>% 
  summarize(SUM_pop = sum(value)) %>%
  data.frame()

merged_London_births_pop_group = left_join(All_london_fempop_agg, All_london_births_agg,
               by=c("year", "age_Cat" = "age_motherCat")) %>%
  data.frame()

ASFR_London_calc_group <- merged_London_births_pop_group %>%
  mutate(ASFR = SUM_births*1000/SUM_pop) %>%
  data.frame()

TFR_London_calc_group <- ASFR_London_calc_group %>%
  group_by(year, age_Cat) %>%
  summarise(SUM_ASFR = sum(ASFR)) %>%
  mutate(TFR = SUM_ASFR*5/1000) %>%
   select(year, SUM_ASFR, TFR) %>%
  data.frame()

```


```{r fig_London_TFR_4, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# # Plotting London ASFR by age-group, over time

ASFR_London_line_group <- ASFR_London_calc_group %>%
  ggplot(aes(x = year, y = ASFR, group = age_Cat, color = age_Cat, text = paste("Year: ", year,
                         "<br>Age group: ", age_Cat,
                         "<br>ASFR: ", round(ASFR, digits = 3))
)) +
  theme_gla() +
  geom_line() +
  ylim(0, 150) +
  labs(title= "Fig 4: AGE SPECIFIC FERTILITY RATE in London by age-category, 1993 - 2021", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

ggplotly(ASFR_London_line_group, tooltip = "text") %>%
    style(hoverlabel = list(bgcolor = "white")) %>%
    layout(title= list(x = 0.05,
         text = "<b>Fig 4: AGE SPECIFIC FERTILITY RATE in London by age-category, 1993 - 2021<b>", 
         font=list(size = 15, family = "Arial")))


```


```{r setup4, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

# Now doing calculations so that can plot ASFR over time by separate age groups, by separate borough

# The first two dataframes are the same as for the calculations above

All_births <- readRDS("C:/Families/Data/Births_by_SYA_1993-2021/births_calendar_year_age_mother_lad.rds") %>%   
  data.frame

All_london_births <- All_births %>%
  filter(grepl('E09000', gss_code)) %>%
  filter(age_mother != "total") %>%
  mutate(age_mother = recode(age_mother, 'Under 20'='19', '40 and over'='41')) %>% 
  mutate(age_mother_num = as.numeric(age_mother)) %>%
  mutate(age_motherCat = cut(age_mother_num, breaks = c(15, 20, 25, 30, 35, 40, 50),
                      right=FALSE,
                      labels = c("15 - 19",
                                 "20 - 24",
                                 "25 - 29",
                                 "30 - 34",
                                 "35 - 39",
                                 "40 - 44"))) %>%
  data.frame()

All_london_births_agg <- All_london_births %>%
  group_by(year, gss_code, gss_name, age_motherCat) %>%
  summarize(SUM_births = sum(value)) %>%
  data.frame()

#-----------------------------------------------------------------------

# Reading population data again for all years from 1993 
# The first two dataframes are the same as for the calculations above

input_pop <-  readRDS("C:/Families/GLA_population/pop_1991_2021_age_0to85plus.rds") %>%   
  data.frame()

# select population for London, and only women
All_london_fempop <- input_pop %>%
  filter(sex == "female") %>%
  filter(grepl('E09000', gss_code)) %>%
  mutate(age_Cat = cut(age, breaks = c(0, 15, 20, 25, 30, 35, 40, 45, 50),
                      right=FALSE,
                      labels = c(" 0 - 14",
                                 "15 - 19",
                                 "20 - 24",
                                 "25 - 29",
                                 "30 - 34",
                                 "35 - 39",
                                 "40 - 44",
                                 "45 - 49"))) %>%
  filter(age_Cat != " 0 - 14") %>%
  filter(age_Cat != "45 - 49") %>%
  data.frame()

All_london_fempop_agg <- All_london_fempop %>%
  group_by(year, gss_code, gss_name, age_Cat) %>% 
  summarize(SUM_pop = sum(value)) %>%
  data.frame()

merged_births_pop = left_join(All_london_fempop_agg, All_london_births_agg,
               by=c("year", "gss_code", "gss_name", "age_Cat" = "age_motherCat")) %>%
  data.frame()

ASFR_calc <- merged_births_pop %>%
  mutate(ASFR = SUM_births*1000/SUM_pop) %>%
  data.frame()

TFR_calc <- ASFR_calc %>%
  group_by(year, gss_code, gss_name, age_Cat) %>%
  summarise(SUM_ASFR = sum(ASFR)) %>%
  mutate(TFR = SUM_ASFR*5/1000) %>%
   select(year, gss_code, gss_name, age_Cat, SUM_ASFR, TFR) %>%
  data.frame()

```

```{r fig_London_TFR_5, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# # Plotting London ASFR by age-group, over time, for each borough (here Merton)

ASFR_2021_line_4 <- ASFR_calc %>%
  filter(gss_name == "Merton") %>%
  ggplot(aes(x = year, y = ASFR, group = age_Cat, color = age_Cat, text = paste("Year: ", year,
                         "<br>Age group: ", age_Cat,
                         "<br>ASFR: ", round(ASFR, digits = 3))
)) +
  theme_gla() +
  geom_line() +
  ylim(0, 150) +
  labs(title= "AGE SPECIFIC FERTILITY RATE in Merton by age-category, 1993 - 2021", 
       caption = paste0("Source: ONS, Chart: GLA demography")) + 
   facet_grid(gss_name ~ .)


ggplotly(ASFR_2021_line_4, tooltip = "text") %>%
    style(hoverlabel = list(bgcolor = "white")) %>%
    layout(title= list(x = 0.05,
         text = "<b>Fig 5: AGE SPECIFIC FERTILITY RATE in Merton by age-category, 1993 - 2021<b>", 
         font=list(size = 15, family = "Arial")))


```